### ISSUE TITLE
Insert image doesn't work

### ISSUE THREAD

**Issue by yshadow** [signintech/pdft#2]
Hi I'm trying to insert a png image to pdf without success:

        var ipdf pdft.PDFt
	err := ipdf.Open(source)
	if err != nil {
		panic("Couldn't open pdf.")
	}

	payload, err := ioutil.ReadFile(signature)
	if err != nil {
		panic("Couldn't read signature.")
	}

	encoded := base64.StdEncoding.EncodeToString(payload)
	fmt.Println(encoded)

	err = ipdf.InsertImgBase64(encoded, 1, 182.0, 165.0, 172.0, 49.0)
	if err != nil {
		panic("Couldn't insert image")
	}

	err = ipdf.Save(target)
	if err != nil {
		panic("Couldn't save pdf.")
	}

**Comment by oneplus1000** [comment]
And I add new function
```go
var ipdf pdft.PDFt
...
ipdf.InsertImg(byteFromJpg, 1, 100.0, 100.0, 100, 100)  //InsertImg() and InsertImgBase64() supported JPG file 
```
*** note

**Comment by yshadow** [comment]
Great, I can confirm it works. Thank you.

**Comment by unclebob2013** [comment]
> And I add new function
> 
> ```go
> var ipdf pdft.PDFt
> ...
> ipdf.InsertImg(byteFromJpg, 1, 100.0, 100.0, 100, 100)  //InsertImg() and InsertImgBase64() supported only jpeg file 
> ```

same issue here but instead insert img become upside down,why?
