### ISSUE TITLE
Can I Add page from another pdf into current pdf object 

### ISSUE THREAD

**Issue by kapong** [signintech/pdft#6]
Can I Add page from another pdf into current pdf object? 

น่าจะเข้าใจภาษาไทย ขออนุญาติพิมพ์เป็นไทย ผมจะสามารถเพิ่มหน้าใหม่เข้ามาได้มั๊ยครับ เช่น จะทำใบเสร็จรับเงิน แต่อาจจะมี 2 แผ่น หรือ 3 แผ่น สามารถทำได้มั๊ยครับ

**Comment by oneplus1000** [comment]
signintech/pdft ไม่ได้ทำ support ไว้เลยครับ 
ที่ผมใช้ภายในจะเป็นแนวนี้ครับคือ สร้าง pdf แยก file (ไฟล์ละหน้า) แล้วใช้ lib ตัวอื่นมารวม file pdf เข้ากันอีกทีครับ

**Comment by kapong** [comment]
พอจะชี้จุดที่มีความเป็นไปได้ที่จะแก้มั๊ยครับ เผื่อผมช่วยแก้ให้ครับ

ตอนนี้พยายามอ่านการ parser แต่ยังมึนส์ๆ

**Comment by oneplus1000** [comment]
ลองเปิด pdf ด้วย text editor ซักตัวดูครับ ลองมองหา obj ที่ type เป็น /Pages
อย่างอันนี้คือ 
```
2 0 obj
<<
  /Type /Pages
  /MediaBox [ 0 0 595.28 841.89 ]
  /Count 1
  /Kids [  4 0 R  ]
>>
endobj

4 0 obj
<<
  /Type /Page
  /Parent 2 0 R
  /Resources 3 0 R
  /Contents  11 0 R 
>>
endobj
```
อันแรกคือ Pages เหมือนตัวบอกว่ามันหน้าอะไรบ้างครับ
-  2 0 obj บอก Id ของ มันเอง คือ 2 0  
- /Type /Pages คือ pages
- /Count 1 ประมาณว่ามีลูกอยู่ 1
-  /Kids [  4 0 R  ] ที่ระบุลูกๆมัน เช่น คือมีลูกคือ id 4 0 ( ถ้ามีลูกหลายๆตัวก็ยัดใส่มาประมาณนี้ครับ  /Kids [  4 0 R  11 0 R 13 0 R] )

อันที่ 2 คือ Page คือข้อมูลของหน้าครับ
-  4 0 obj บอก Id ของ มันเอง คือ 4 0 
- /Parent 2 0 R คือ id ของ /Pages 
- /Resources 3 0 R ที่ระบุ id ของพวก resources ต่างๆที่ต้องใช้ในหน้าครับ เช่น font file, รูป 
-  /Contents 11 0 R  ที่ระบุ id เนื้อหาของหน้านี้

### วิธีก็คือ
- ต้องเพิ่ม obj /Page ขึ้นมาทั้งอันแล้วยัดกลับไปยัง /Kids ของ  obj /Pages ครับ  
- และต้องสร้าง /Resources /Contents obj ขึ้นมาใหม่ (แต่คิดว่าเป็น obj ว่างๆน่าจะพอเพราะพวก func Insert เดิมน่าจะจัดการยัดข้อมูลจริงเข้า  /Resources /Contents ให้อยู่แล้ว )

####  _/Resources กับ /Contents ว่างๆหน้าตาน่าจะประมาณนี้ครับ_
#### - obj /Resources
```
3 0 obj
<<
/ProcSet [/PDF /Text /ImageB /ImageC /ImageI]
/Font <<
>>
/XObject <<
>>
>>
endobj
```
#### - obj /Contents
```
11 0 obj
<<
/Filter/FlateDecode/Length 0
>>
stream
endstream
endobj
```
หมายเหตุ: ขอออกตัวนิดนะครับว่าผมเขียนมาจากความทรงจำอาจจะผิดได้

**Comment by kapong** [comment]
ขอบคุณครับ ขอ fork ไปพยายามลองเขียนก่อนนะครับ 

ถ้าผ่านจะมาขอ merge request
